# -*- coding: utf-8 -*-
"""Stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17w4BaxDN7ArgQk1LcYjyK8Rsv-upZsJE

## **Setting up Enrivoment**
"""

import pandas as pd
import numpy as np
import statistics
from scipy.stats import iqr
import matplotlib.pyplot as plt

"""## **Content**

The data set contains over two decades of data on each player who has been part of an NBA teams' roster. It captures demographic variables such as age, height, weight and place of birth, biographical details like the team played for, draft year and round. In addition, it has basic box score statistics such as games played, average number of points, rebounds, assists, etc.
"""

#Loading NBA Player Dataset
data = pd.read_csv('/content/drive/MyDrive/all_seasons.csv')
data.head()

data.info()

"""## **Measures of Center**
Measures of centre help us understand the central tendency or the typical value of a dataset. Let's explore the three key measures of centre:

*   Mean
*   Median
*   Mode

### **Mean**

Also known as the arithmetic mean or average, is a measure of centre calculated by summing up all the values in a dataset and dividing the sum by the total number of observations. It provides a measure of the central tendency of the data by taking into account all values. The mean is sensitive to extreme values and can be affected by outliers.

**When to use the mean**

It is suitable for symmetrically distributed data without extreme outliers. The mean is especially useful when you need to calculate the average or estimate a central value.

**The formula for Mean:**

Mean = (Sum of all values) / (Number of observations)
"""

#plotting histogrom of player_height
plt.hist(data['player_height'])

plt.show()

"""The player_height column is symmetrical, so we can go ahead and calculate the mean"""

#Calculating the mean of player_height(in centimeters)

mean = np.mean(data['player_height'])

print(mean)

"""The mean or average height of NBA players is ~200.611 cm

### **Median**
The median is the middle value in a dataset when it is sorted in ascending order. It is a robust measure of centre that is less affected by extreme values or skewed data distributions.To calculate the median, the dataset is first sorted in ascending or descending order. Then, the middle value is determined. If the dataset has an odd number of observations, the median is simply the middle value. However, if the dataset has an even number of observations, the median is calculated as the average of the two middle values.

**When to use median**

It is particularly useful when working with datasets that contain outliers or when you want to describe the typical value without being influenced by extreme observations.

**The formula for median**

*Odd number of observations:*

Consider the dataset [2, 5, 7, 9, 12]. When sorted in ascending order, the middle value is 7. Therefore, the median of this dataset is 7.

*Even number of observations:*

Let's take the dataset [4, 6, 8, 10, 14, 16]. When sorted in ascending order, the two middle values are 8 and 10. To find the median, calculate their average: (8 + 10) / 2 = 9. Therefore, the median of this dataset is 9.
"""

plt.hist(data['pts'])

plt.show()

"""Since the data for average points scored is Right-skewed we can go ahead and calculate the median points scored by an NBA player"""

median = np.median(data['pts'])

print(median)

"""This indicates that half of the NBA players have an average points scored that is lower than approximately 6.7 to 7, while the other half has an average points scored that is higher than 6.7 to 7.

### **Mode**
The mode is a measure of centre that represents the value or values that occur most frequently in a dataset. It is particularly useful when analysing categorical or discrete data.
"""

mode = statistics.mode(data['country'])

mode

"""The result indicates that the most common country in the dataset is USA

## **Measures of Spread**
Measures of spread also referred to as measures of dispersion, are statistical tools that help us understand how the data points in a dataset are spread out or dispersed around a central value, such as the mean or median. These measures provide valuable insights into the variability present in the dataset and enable us to assess the extent of spread among the data points.

### **Variance**

Variance is a statistical measure that quantifies the spread or dispersion of data points in a dataset. It provides a numerical representation of how much the individual values deviate from the mean. In other words, variance measures the average squared difference between each data point and the mean of the dataset.
"""

#calculating the variance
variance = np.var(data['player_height'], ddof=1)

variance

"""### **Standard Deviation**
The standard deviation is the square root of the variance and provides a more interpretable measure of spread. It indicates the typical distance between data points and the mean.

**The formula for calculating the standard deviation:**

Standard Deviation = √((Σ(xᵢ - μ)²) / n)

"""

Standard_Deviation = np.std(data['player_height'], ddof=1)

Standard_Deviation

"""### **Mean Absolute Deviation**

Mean Absolute Deviation (MAD) is a statistical measure that quantifies the average absolute difference between each data point and the mean of a dataset. It provides a measure of the dispersion or spread of data points around the mean.

**The formula for calculating the MAD:**

MAD = (|x₁ - μ| + |x₂ - μ| + ... + |xₙ - μ|) / n


"""

mad = data['player_height'] - mean

np.mean(np.abs(mad))

"""### **Quantiles**
Quantiles divide a dataset into equal portions, enabling us to analyse data distribution and compare values across different datasets.

Median (2nd Quantile):

The median, as discussed earlier, represents the middle value of a dataset. It is the 50th percentile, dividing the data into two equal parts.
"""

np.quantile(data['player_height'], 0.5)

"""**Quartiles (1st, 2nd, and 3rd Quantiles):**

Quartiles divide the data into four equal parts, representing the 25th, 50th, and 75th percentiles. The first quartile (Q1) represents the lower 25% of the data, the second quartile (Q2) represents the median, and the third quartile (Q3) represents the upper 25% of the data.

"""

np.quantile(data['player_height'], [0, 0.25, 0.5, 0.75, 1])

"""### **Boxplots use quartiles**"""

plt.boxplot(data['player_height'])

plt.show()

"""### **Inter quartile rang (iqr)**

The Interquartile Range (IQR) is a statistical measure that represents the spread or dispersion of the middle 50% of the data in a dataset. It is calculated as the difference between the third quartile (Q3) and the first quartile (Q1).
"""

IQR = iqr(data['player_height'])

IQR